add ping config
youngmonkeys/ezyfox-server-swift-client pull request #3
Opened 2021-09-04 08:43 UTC by tvd12

2021-09-07 13:32 UTC, vu-luong requested changes
Anh add thêm `How to test?` vào README giúp em với ạ.

2021-09-09 04:03 UTC, vu-luong requested changes
Em thấy code ok rồi anh ạ. Anh add thêm `How to test?` vào README là ok ạ.

2021-09-09 10:32 UTC, tvd12 commented
> Em thấy code ok rồi anh ạ. Anh add thêm `How to test?` vào README là ok ạ.

Mình sẽ tạo 1 PR riêng em ạ

2021-09-09 10:55 UTC, vu-luong approved these changes
LGTM!

2021-09-09 16:05 UTC, merged